### PR TITLE
Add support for calibratable parameters (lumped version)

### PR DESCRIPTION
**Pull request by GreyEvenson-NOAA**
# Purpose

This PR exposes the model's calibratable parameters via its BMI so that they can be calibrated via NextGen. This PR exposes these parameters in the lumped (i.e., non-gridded) version of Noah-OWP-Modular.

# Additions

## Calibratable parameters

The following parameters were added to the model's BMI:
- `BEXP`
- `SMCMAX`
- `DKSAT`
- `RSURF_EXP`
- `REFKDT`
- `AXAJ`
- `BXAJ`
- `XXAJ`
- `SLOPE`
- `CWP`
- `VCMX25`
- `MP`
- `MFSNO`
- `SCAMAX`***
- `RSURF_SNOW`
- `HVT`
- `FRZX`**
- `KDT`**

** `FRZX` and `KDT` were added because they are recalculated/reinitialized when setting `SMCMAX`, `DKSAT` and/or `REFKDT`. `FRZX` and `KDT` were added so that they may be included in the unit test program; they are not intended to be calibrated.

*** This PR adds `SCAMAX` to Noah-OWP-Modular because it is a NWM 3.0 calibratable parameter. `SCAMAX` was added as a member of `parameters_type`. The calculation of `FSNO` (i.e., snow covered area) was amended to follow [WRF-Hydro's calculation](https://github.com/NCAR/wrf_hydro_nwm_public/blob/3deb607cd07236794af3140d4778d7da2d776b5e/src/Land_models/NoahMP/phys/module_sf_noahmplsm.F#L1839) as:

`water%FSNO   = parameters%SCAMAX * TANH( water%SNOWH /(2.5 * parameters%Z0 * FMELT))`

# Changes

The Noah-OWP-Modular unit test program (`/test/noahowp_driver_test.f90`) was updated to facilitate testing of the calibratable parameters.

# Testing

The refactored unit test program was executed and gave these [results](https://github.com/NOAA-OWP/noah-owp-modular/files/14578165/noahowp_test_output.txt).

# Notes

This PR replicates PR #95, which exposed the calibratable parameters for the gridded version of Noah-OWP-Modular.

### CODE REVIEW

**Comment by GreyEvenson-NOAA** [comment]
Ngen integration tests may be failing due to [NGEN issue #751](https://github.com/NOAA-OWP/ngen/issues/761).

**Comment by drakest123** [comment]
PR #102 Review
- No issues were found by code inspection
- Note that case statements would be slightly easier to read if the test variables were in ~ alphabetical order
- Addition of trim() function in test/noahowp_driver_test.f90 improves robustness of test routine
- Most of the changes were boilerplate additions to bmi_noahowp.f90 and test/noahowp_driver_test.f90 .
- Compiled and executed:
run/noah_owp_modular.exe
test/noahowp_test.exe ../run/namelist.input > output_test
- There is no difference between the test output and that posted with the PR:
% diff ~/Downloads/noahowp_test_output.txt output_test 

The NGen integration tests indicate that a shared library called “register_bmi” is missing. I don't know the significance of these checks.

**Review by drakest123 — CHANGES_REQUESTED** [review]
Request that case statements be rearranged to alphabetical order to facilitate code readability.

**Comment by GreyEvenson-NOAA** [comment]
Thanks for your review, @drakest123. I put the BMI case listings in alphabetical order for easier reading.

**Pull request merged**
